-- SQLite

CREATE TABLE KEYWORD(
    ID INTEGER not null,
	WORD NVARCHAR(50) not nulL,
	PRIMARY KEY(ID, WORD)
    );

CREATE TABLE ARTICLES(
    ID INTEBER NOT NULL,
    URL NVARCHER(3000) NOT NULL,
    KEYWORD_ID INTEGER NOT NULL,
    TITLE TEXT,
    CONTENT TEXT,
    LENGTH INT,
    PRIMARY KEY(ID, URL)
);