NAVER:
  CLIENT_ID: iLSTcLpJKsaBETLkEHOq
  CLIENT_SECRET_ID: _SBXwc4_ht

GOOGLE:
  CLIENT_ID: 
  CLIENT_SECRET_ID: 

DB:
  TYPE: mysql
  HOST: localhost
  PORT: 2244
  DATABASE: gendoc
  USER: root
  PASSWORD: "1234"