ADMIN_ID: order@dhej.com
ADMIN_PASSWD: gAAAAABgm84A0XitBsR8g48lSq_9Q0oWgeO_R3BzBEtZwZZQreYbqH9eu3WUjO8HVxIj0EyyjIjksWI1jf33osR5qGEpIkXAcg==
DOWNLOAD_FORM: c2021012565e3479783b78
HOMEPATH: /var/www/html/ADMOVE
TIMER: '14:00'
